# Generated by Django 4.2.8 on 2023-12-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacaton_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nametest',
            name='user_done',
            field=models.ManyToManyField(null=True, to='hacaton_site.student', verbose_name='Юзеры прошедшие тест'),
        ),
    ]
